name: Build

on:
  push:
    branches:
      - main
      - v-next
  pull_request:
    branches:
      - main
      - v-next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: '10.0.x' # Adjust the version as needed

    - name: Clean up previous builds
      run: dotnet clean src/AzUrlShortener.sln

    - name: Install Aspire workload
      run: dotnet workload update && dotnet workload install aspire

    - name: Restore dependencies
      run: dotnet restore src/AzUrlShortener.sln

    - name: Build solution
      run: dotnet build src/AzUrlShortener.sln --no-restore --configuration Release

    - name: Set up Node.js for SPFx
      uses: actions/setup-node@1e60f620b9541d13bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: '22.x'
        cache: npm
        cache-dependency-path: src/AdminWebPart/package-lock.json

    - name: Install SPFx dependencies
      working-directory: src/AdminWebPart
      run: npm ci --no-audit

    - name: Build SPFx administration web part
      working-directory: src/AdminWebPart
      run: npm run build
